name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install flake8 flask==3.0.0

      - name: Lint Python code
        run: flake8 app/main.py --max-line-length=100

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Validate Helm chart
        run: helm lint helm/skybyte-app/

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format Check
        run: terraform -chdir=terraform/ fmt -check

  build-docker:
    runs-on: ubuntu-latest
    needs: lint-and-validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t skybyte-app:${{ github.sha }} .

      - name: Verify image exists
        run: docker images skybyte-app
